### ISSUE TITLE
ControlFlow::WaitUntil seems to not work on Windows10, causing high CPU usage

### ISSUE THREAD

**Issue by I3ck** [rust-windowing/winit#1610]
The following example causes basically no CPU usage on Linux, but causes high usage on Windows.  
I tried fixing the issue with a combination of `Poll` and `thread::sleep()`. But this causes interactions to become laggy/unresponsive.  
If there's a workaround please let me know.
  
Cargo.toml
```toml
[package]
name = "reproducer"
version = "0.0.1"
authors = ["nobody"]
edition = "2018"

[[bin]]
name = "reproducer"
path = "src/main.rs"

[dependencies]
gl = "0.14.0"
glutin = "0.24.1"
```
src/main.rs
```rust
pub fn main() {
    let el = glutin::event_loop::EventLoop::new();

    let wb = glutin::window::WindowBuilder::new()
        .with_title("Reproducer")
        .with_inner_size(glutin::dpi::PhysicalSize::new(
            400,
            400,
        ));
    let windowed_context = glutin::ContextBuilder::new()
        .with_gl_profile(glutin::GlProfile::Core)
        .with_gl(glutin::GlRequest::Specific(glutin::Api::OpenGl, (3, 3)))
        .build_windowed(wb, &el)
        .unwrap();

    let windowed_context =
        unsafe { windowed_context.make_current().unwrap() };

    gl::load_with(|symbol| windowed_context.get_proc_address(symbol) as *const _);

    unsafe {
        gl::Enable(gl::DEPTH_TEST);
        gl::Enable(gl::BLEND);
        gl::ClearColor(0.1, 0.1, 0.1, 1.0);
    }

    el.run(move |_event, _, control_flow| {
        *control_flow = glutin::event_loop::ControlFlow::WaitUntil(std::time::Instant::now() + std::time::Duration::from_millis(1));
    });
}
```
