### ISSUE TITLE
Getting access to precise delta times in web targets

### ISSUE THREAD

**Issue by leod** [rust-windowing/winit#1697]
Some browsers implement measures which prevent getting accurate time information on the level of milliseconds (thanks to spectre/meltdown). This can lead to choppy movement in games that rely on delta times. Quoting from https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp:
> To offer protection against timing attacks and fingerprinting, the precision of time stamps might get rounded depending on browser settings. In Firefox, the privacy.reduceTimerPrecision preference is enabled by default and defaults to 20 µs in Firefox 59; in 60 it will be 2ms.

A similar note can be found on the documentation for [Date.now](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now).

Now, as a workaround, one can make use of the fact that the `requestAnimationFrame` callback is also given the elapsed time. As far as I can tell, the precision of this is not fuzzed, or at least not as much. Feel free to try this yourself, e.g. with this [example](https://gist.github.com/leod/0f918fbd49e2b34b963f288914b231d7).

Here's an excerpt of the delta times that I get in Firefox 79 and Chrome on Ubuntu:
```
Firefox: 
  deltas_timestamp: 16.139999999999873,17.059999999999945,16.080000000000155,17.079999999999927,16.059999999999945,17.060000000000173,17.079999999999927,16.059999999999945,17.059999999999945,16.080000000000155,17.059999999999945,17.079999999999927,16.060000000000173,17.059999999999945,16.059999999999945
  deltas_performance: 17,17,17,17,16,17,16,17,16,17,17,16,18,15,18

Chrome:
  deltas_timestamp: 16.66599999999994,16.666000000000167,16.66599999999994,16.66599999999994,16.66599999999994,16.666000000000167,16.66599999999994,16.66599999999994,16.666000000000167,16.66599999999994
  deltas_performance: 16.445000000203436,16.669999999976426,16.649999999572174,16.644999999698484,16.75000000068394,16.614999999546853,16.68500000050699,16.644999999698484,16.674999999850115,16.665000000102737,16.684999999597494,16.64000000073429,16.759999999521824,16.630000000077416,16.644999999698484
```
(`delta_timestamp` is the argument to `requestAnimationFrame`, `delta_performance` is based on `performance.now()`)

I believe that winit is currently not making use of the timestamp passed to `requestAnimationFrame` (https://github.com/rust-windowing/winit/blob/1f24a09570d3bf0a39af836c3a7c212a0b65ff70/src/platform_impl/web/web_sys/timeout.rs#L61). This is a reasonable choice, since I assume winit wants to leave handling of time to the user. However, this is making it difficult to work around browsers reducing the precision of time information.

Would there be any way to expose the timestamp passed to `requestAnimationFrame` in winit to users?
